#!/bin/bash

# add use mpistub for single-core version
sed -i 's/!use mpistub/use mpistub/g' ../src/Contrl/Input.f90
sed -i 's/!use mpistub/use mpistub/g' ../src/DataStruct/Data.f90
sed -i 's/!use mpistub/use mpistub/g' ../src/DataStruct/PhysConst.f90
sed -i 's/!use mpistub/use mpistub/g' ../src/DataStruct/Pgrid.f90
sed -i 's/!use mpistub/use mpistub/g' ../src/Func/Timer.f90

cp ../src/mpif.h ../src/Appl 
cp ../src/mpif.h ../src/Contrl
cp ../src/mpif.h ../src/DataStruct 
cp ../src/mpif.h ../src/Func 

# add mpistub.o into makefile
sed -i 's/OBJS = \\/OBJS =  mpistub.o \\/g' ../src/Makefile
sed -i 's/OBJS2 = \\/OBJS2 =  mpistub.o \\/g' ../src/Makefile

# change mpif90 compiller to gfortran
sed -i 's/mpif90/gfortran/g' ../src/Makefile
